
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ConfigData : Luban.BeanBase
{
    public ConfigData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["value1"].IsNumber) { throw new SerializationException(); }  Value1 = _buf["value1"]; }
        { if(!_buf["value2"].IsString) { throw new SerializationException(); }  Value2 = _buf["value2"]; }
    }

    public static ConfigData DeserializeConfigData(JSONNode _buf)
    {
        return new ConfigData(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 值1
    /// </summary>
    public readonly int Value1;
    /// <summary>
    /// 值2
    /// </summary>
    public readonly string Value2;
   
    public const int __ID__ = -1470475732;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "value1:" + Value1 + ","
        + "value2:" + Value2 + ","
        + "}";
    }
}

}

