
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Level : Luban.BeanBase
{
    public Level(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["levelnumber"].IsNumber) { throw new SerializationException(); }  Levelnumber = _buf["levelnumber"]; }
        { if(!_buf["levelGraphPath"].IsString) { throw new SerializationException(); }  LevelGraphPath = _buf["levelGraphPath"]; }
        { if(!_buf["levelBossGraphPath"].IsString) { throw new SerializationException(); }  LevelBossGraphPath = _buf["levelBossGraphPath"]; }
    }

    public static Level DeserializeLevel(JSONNode _buf)
    {
        return new Level(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属大关
    /// </summary>
    public readonly int Levelnumber;
    /// <summary>
    /// 关卡普通布局路径
    /// </summary>
    public readonly string LevelGraphPath;
    /// <summary>
    /// 关卡boss关布局路径
    /// </summary>
    public readonly string LevelBossGraphPath;
   
    public const int __ID__ = 73313124;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "levelnumber:" + Levelnumber + ","
        + "levelGraphPath:" + LevelGraphPath + ","
        + "levelBossGraphPath:" + LevelBossGraphPath + ","
        + "}";
    }
}

}

