
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Player : Luban.BeanBase
{
    public Player(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["skill"].IsString) { throw new SerializationException(); }  Skill = _buf["skill"]; }
        { if(!_buf["hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["hp"]; }
        { if(!_buf["shield"].IsNumber) { throw new SerializationException(); }  Shield = _buf["shield"]; }
        { if(!_buf["speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["speed"]; }
        { if(!_buf["mp"].IsNumber) { throw new SerializationException(); }  Mp = _buf["mp"]; }
        { if(!_buf["Initialweapon"].IsString) { throw new SerializationException(); }  Initialweapon = _buf["Initialweapon"]; }
    }

    public static Player DeserializePlayer(JSONNode _buf)
    {
        return new Player(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 角色名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 角色可用的技能id
    /// </summary>
    public readonly string Skill;
    /// <summary>
    /// 初始生命值
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 初始护盾值
    /// </summary>
    public readonly int Shield;
    /// <summary>
    /// 初始速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 初始魔法值
    /// </summary>
    public readonly int Mp;
    /// <summary>
    /// 初始武器对应id
    /// </summary>
    public readonly string Initialweapon;
   
    public const int __ID__ = -1901885695;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "skill:" + Skill + ","
        + "hp:" + Hp + ","
        + "shield:" + Shield + ","
        + "speed:" + Speed + ","
        + "mp:" + Mp + ","
        + "Initialweapon:" + Initialweapon + ","
        + "}";
    }
}

}

