
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbItem TbItem {get; }
    public TbRoom TbRoom {get; }
    public TBConfigData TBConfigData {get; }
    public TBLevel TBLevel {get; }
    public TBCharacter TBCharacter {get; }
    public TBWeapon TBWeapon {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbItem = new TbItem(loader("tbitem"));
        TbRoom = new TbRoom(loader("tbroom"));
        TBConfigData = new TBConfigData(loader("tbconfigdata"));
        TBLevel = new TBLevel(loader("tblevel"));
        TBCharacter = new TBCharacter(loader("tbcharacter"));
        TBWeapon = new TBWeapon(loader("tbweapon"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbRoom.ResolveRef(this);
        TBConfigData.ResolveRef(this);
        TBLevel.ResolveRef(this);
        TBCharacter.ResolveRef(this);
        TBWeapon.ResolveRef(this);
    }
}

}
