
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TBConfigData
{
    private readonly System.Collections.Generic.Dictionary<int, ConfigData> _dataMap;
    private readonly System.Collections.Generic.List<ConfigData> _dataList;
    
    public TBConfigData(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ConfigData>();
        _dataList = new System.Collections.Generic.List<ConfigData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ConfigData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ConfigData.DeserializeConfigData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ConfigData> DataMap => _dataMap;
    public System.Collections.Generic.List<ConfigData> DataList => _dataList;

    public ConfigData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ConfigData Get(int key) => _dataMap[key];
    public ConfigData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

