
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TBEnemy
{
    private readonly System.Collections.Generic.Dictionary<int, Enemy> _dataMap;
    private readonly System.Collections.Generic.List<Enemy> _dataList;
    
    public TBEnemy(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Enemy>();
        _dataList = new System.Collections.Generic.List<Enemy>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Enemy _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Enemy.DeserializeEnemy(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Enemy> DataMap => _dataMap;
    public System.Collections.Generic.List<Enemy> DataList => _dataList;

    public Enemy GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Enemy Get(int key) => _dataMap[key];
    public Enemy this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

