
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TBPet
{
    private readonly System.Collections.Generic.Dictionary<int, Pet> _dataMap;
    private readonly System.Collections.Generic.List<Pet> _dataList;
    
    public TBPet(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Pet>();
        _dataList = new System.Collections.Generic.List<Pet>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Pet _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Pet.DeserializePet(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Pet> DataMap => _dataMap;
    public System.Collections.Generic.List<Pet> DataList => _dataList;

    public Pet GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Pet Get(int key) => _dataMap[key];
    public Pet this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

