
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbRoom
{
    private readonly System.Collections.Generic.Dictionary<int, Room> _dataMap;
    private readonly System.Collections.Generic.List<Room> _dataList;
    
    public TbRoom(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Room>();
        _dataList = new System.Collections.Generic.List<Room>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Room _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Room.DeserializeRoom(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Room> DataMap => _dataMap;
    public System.Collections.Generic.List<Room> DataList => _dataList;

    public Room GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Room Get(int key) => _dataMap[key];
    public Room this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

