
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Weapon : Luban.BeanBase
{
    public Weapon(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["damage"]; }
        { if(!_buf["mc"].IsNumber) { throw new SerializationException(); }  Mc = _buf["mc"]; }
        { if(!_buf["probability"].IsNumber) { throw new SerializationException(); }  Probability = _buf["probability"]; }
        { if(!_buf["price"].IsString) { throw new SerializationException(); }  Price = _buf["price"]; }
    }

    public static Weapon DeserializeWeapon(JSONNode _buf)
    {
        return new Weapon(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 初始伤害值
    /// </summary>
    public readonly int Damage;
    /// <summary>
    /// 初始每发蓝耗
    /// </summary>
    public readonly int Mc;
    /// <summary>
    /// 随机时出现的概率
    /// </summary>
    public readonly int Probability;
    /// <summary>
    /// 出现在商店时的底价（还要经过计算）
    /// </summary>
    public readonly string Price;
   
    public const int __ID__ = -1707954628;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "damage:" + Damage + ","
        + "mc:" + Mc + ","
        + "probability:" + Probability + ","
        + "price:" + Price + ","
        + "}";
    }
}

}

